package enums.TestCaseFields;

public enum TestCaseType {
    ACCEPTANCE,
    ACCESSIBILITY,
    AUTOMATED,
    COMPATIBILITY,
    DESTRUCTIVE,
    FUNCTIONAL,
    OTHER,
    PERFORMANCE,
    REGRESSION,
    SECURITY,
    SMOKE_AND_SANITY,
    USABILITY
}
